hosts:
  configuration:
    &hostsConfig # This is a YAML anchor for reusability and readability
    baseHost: theia-test.artemis.cit.tum.de
    service: service.test1
    landing: test1
    instance: instance.test1

theia-certificates:
  hosts:
    configuration: *hostsConfig

theia-cloud:
  app:
    id: nJV3nKZmpxTD4wu2
    name: Artemis Online IDE (Test1)

  issuer:
    email: ls1.itg@in.tum.de

  hosts:
    configuration: *hostsConfig
    allWildcardInstances: ["*.webview."]

  gateway:
    enabled: true
    create: false
    routes:
      enabled: true
    className: envoy
    name: theia-cloud-gateway
    parentRefs:
      - name: theia-shared-gateway
        namespace: gateway-system
    instancesRouteName: "theia-cloud-demo-ws-route"
    instancesWildcardSecretNames: { "*.webview.": static-theia-cert }
    serviceRouteRequestTimeout: "60s"

  monitor:
    enable: true
    activityTracker:
      enable: true
      interval: 3

  operator:
    #image: ghcr.io/eduide/eduide/operator:latest
    #eagerStart: false
    replicas: 1
    sessionsPerUser: 1000 # Needed for load tests - not recommended for production
    storageClassName: csi-rbd-sc

  # service:
  #   image: ghcr.io/eduide/eduide/service:latest

  preloading:
    images:
      - ghcr.io/eduide/eduide/landing-page:latest
      - ghcr.io/eduide/eduide/java-17:latest
      - ghcr.io/eduide/eduide/c:latest
      - ghcr.io/eduide/eduide/javascript:latest
      - ghcr.io/eduide/eduide/ocaml:latest
      - ghcr.io/eduide/eduide/rust:latest
      - ghcr.io/eduide/eduide/python:latest

  imagePullPolicy: Always

  # Do not install demoApplication
  demoApplication:
    install: false

  landingPage:
    # We use the try now page as landing page since the default does not support mutliple apps -> https://github.com/eclipsesource/theia-cloud/discussions/301
    image: ghcr.io/eduide/eduide/landing-page
    # We can define a default blueprint
    appDefinition: "java-17-latest"
    ephemeralStorage: true
    additionalApps:
      java-17-latest:
        label: Java 17
      c-latest:
        label: C
      javascript-latest:
        label: Javascript
      ocaml-latest:
        label: Ocaml
      python-latest:
        label: Python
      rust-latest:
        label: Rust
    infoTitle: "Welcome to Theia Test 1"
    infoText: ""
    loadingText: "Preparing your personal Online IDE..."
    footerLinks:
      attribution:
        text: "Built by TUM LS1 Team 👨‍💻"
        url: "https://aet.cit.tum.de/"
        version: "Test1-v1.0.0"
      bugReport:
        text: "Report a bug 🐛"
        url: "https://github.com/ls1intum/theia-cloud/issues"
      featureRequest:
        text: "Request a feature ✨"
        url: "https://github.com/ls1intum/theia-cloud/issues"
      about:
        text: "About"
        url: "https://aet.cit.tum.de/"


  keycloak:
    enable: true

    # -- Key cloak auth URL. Only has to be specified when enable: true
    authUrl: "https://keycloak.ase.in.tum.de/"

    # -- The Keycloak Realm. Only has to be specified when enable: true
    realm: "Test"

    # -- The client-id. Only has to be specified when enable: true
    clientId: "theia-test"

monitoring:
  targetNamespaces:
    - test1
  sessionNamespaces:
    - test1
