{{- if .Values.envoyProxy.create }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.envoyProxy.name }}
  namespace: {{ .Values.envoyProxy.namespace }}
  {{- with .Values.envoyProxy.labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.envoyProxy.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ toYaml .Values.envoyProxy.spec | nindent 2 }}
{{- end }}
