{{- if gt (len .Values.gateway.listeners) 0 }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  {{- with .Values.gateway.labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  {{- with .Values.gateway.addresses }}
  addresses:
  {{- range $address := . }}
  - type: IPAddress
    value: {{ $address | quote }}
  {{- end }}
  {{- end }}
  listeners:
  {{- range $listener := .Values.gateway.listeners }}
  - name: {{ $listener.name }}
    protocol: HTTPS
    port: 443
    hostname: {{ $listener.hostname | quote }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ $listener.tlsSecretName | quote }}
    allowedRoutes:
{{ toYaml (default $.Values.gateway.allowedRoutes $listener.allowedRoutes) | nindent 6 }}
  {{- end }}
{{- end }}
