{{- if .Values.wildcardTLSSecret.create }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.wildcardTLSSecret.name }}
  namespace: {{ .Values.wildcardTLSSecret.namespace }}
data:
  tls.crt: {{ .Values.wildcardTLSSecret.certificate | quote }}
  tls.key: {{ .Values.wildcardTLSSecret.key | quote }}
{{- end }}
