# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: shared-theia-cert
#   namespace: gateway-system
# spec:
#   secretName: shared-theia-cert
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-prod
#   dnsNames:
#     - test1.theia-test.artemis.cit.tum.de
#     - service.test1.theia-test.artemis.cit.tum.de
#     - instance.test1.theia-test.artemis.cit.tum.de
#     - test2.theia-test.artemis.cit.tum.de
#     - service.test2.theia-test.artemis.cit.tum.de
#     - instance.test2.theia-test.artemis.cit.tum.de
#     - cache.test2.theia-test.artemis.cit.tum.de   # NEW
#     - repo.test2.theia-test.artemis.cit.tum.de    # NEW
#     - test3.theia-test.artemis.cit.tum.de
#     - service.test3.theia-test.artemis.cit.tum.de
#     - instance.test3.theia-test.artemis.cit.tum.de
#     - theia-staging.artemis.cit.tum.de
#     - service.theia-staging.artemis.cit.tum.de
#     - instance.theia-staging.artemis.cit.tum.de