app:
  id: nJV3nKZmpxTD4wu2
  name: Artemis Online IDE

issuer:
  email: ls1.itg@in.tum.de

hosts:
  configuration:
    baseHost: artemis.cit.tum.de
    service: service.theia
    landing: theia
    instance: instance.theia
  allWildcardInstances: ["*.webview."]

gateway:
  enabled: true
  create: true
  routes:
    enabled: true
  className: envoy
  name: theia-cloud-gateway
  parentRefs: []
  instancesWildcardSecretNames: { "*.webview.": static-theia-cert }
  serviceRouteRequestTimeout: "60s"

monitor:
  enable: true
  activityTracker:
    enable: true
    interval: 3

operator:
  image: ghcr.io/ls1intum/theia/operator:pr-41
  eagerStart: false
  replicas: 1
  sessionsPerUser: 10
  storageClassName: csi-rbd-sc
  enableCaching: true
  cacheUrl: "http://theia-shared-cache:5071"

service:
  adminApiTokenSecret:
    name: service-admin-api-token
    key: ADMIN_API_TOKEN
  image: theiacloud/theia-cloud-service:1.1.0-next

preloading:
  images:
    - ghcr.io/eduide/eduide/landing-page:latest
    - ghcr.io/eduide/eduide/java-17:latest
    - ghcr.io/eduide/eduide/c:latest
    - ghcr.io/eduide/eduide/javascript:latest
    - ghcr.io/eduide/eduide/ocaml:latest
    - ghcr.io/eduide/eduide/rust:latest
    - ghcr.io/eduide/eduide/python:latest

imagePullPolicy: Always

# Do not install demoApplication
demoApplication:
  install: false

landingPage:
  # We use the try now page as landing page since the default does not support mutliple apps -> https://github.com/eclipsesource/theia-cloud/discussions/301
  image: ghcr.io/eduide/eduide/landing-page
  # We can define a default blueprint
  appDefinition: "java-17-latest"
  ephemeralStorage: true
  additionalApps:
    java-17-latest:
      label: Java
    c-latest:
      label: C
    javascript-latest:
      label: Javascript
    ocaml-latest:
      label: Ocaml
    python-latest:
      label: Python
    rust-latest:
      label: Rust
  infoTitle: "Welcome to Theia - your tailor-made online IDE"
  infoText: "We are offering a online programming environment perfectly fitting for your project, please log in to continue."
  loadingText: "Preparing your personal Online IDE..."
  footerLinks:
      attribution:
        text: "Built by TUM LS1 Team 👨‍💻"
        url: "https://aet.cit.tum.de/"
        version: "v1.0.0"
      bugReport:
        text: "Report a bug 🐛"
        url: "https://github.com/ls1intum/theia-cloud/issues"
      featureRequest:
        text: "Request a feature ✨"
        url: "https://github.com/ls1intum/theia-cloud/issues"
      about:
        text: "About"
        url: "https://ase-website-test.ase.cit.tum.de/"

keycloak:
  enable: true
  # -- Key cloak auth URL. Only has to be specified when enable: true
  authUrl: "https://keycloak.ase.in.tum.de/"
