apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: theia-cloud-reposilite
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reposilite
  namespaceSelector:
    matchNames:
      {{- range .Values.reposiliteNamespaces }}
      - {{ . }}
      {{- end }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s