---
# This Secret is only needed for the reposilite metrics endpoint. The metrics dont need to be secure, so the credentials are written in plain text
apiVersion: v1
kind: Secret
metadata:
  name: reposilite-prometheus-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: "prometheus"
  password: "prometheus"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: theia-cloud-reposilite
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reposilite
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      basicAuth:
        username:
          name: reposilite-prometheus-credentials
          key: username
        password:
          name: reposilite-prometheus-credentials
          key: password
