gateway:
  name: theia-shared-gateway
  namespace: gateway-system
  className: envoy

  allowedRoutes:
    namespaces:
      from: All

  listeners:
    - name: prod-landing
      protocol: HTTPS
      port: 443
      hostname: theia.artemis.cit.tum.de
      tlsSecretName: landing-page-cert-secret
    - name: prod-service
      protocol: HTTPS
      port: 443
      hostname: service.theia.artemis.cit.tum.de
      tlsSecretName: service-cert-secret
    - name: prod-instances
      protocol: HTTPS
      port: 443
      hostname: instance.theia.artemis.cit.tum.de
      tlsSecretName: ws-cert-secret
    - name: prod-webview
      protocol: HTTPS
      port: 443
      hostname: "*.webview.instance.theia.artemis.cit.tum.de"
      tlsSecretName: static-theia-cert
    - name: prod-cache
      protocol: HTTPS
      port: 443
      hostname: cache.theia.artemis.cit.tum.de
      tlsSecretName: cache-cert-secret
    - name: prod-repo
      protocol: HTTPS
      port: 443
      hostname: repo.theia.artemis.cit.tum.de
      tlsSecretName: repo-cert-secret
    - name: acme-landing-http
      protocol: HTTP
      port: 80
      hostname: theia.artemis.cit.tum.de
    - name: acme-service-http
      protocol: HTTP
      port: 80
      hostname: service.theia.artemis.cit.tum.de
    - name: acme-instance-http
      protocol: HTTP
      port: 80
      hostname: instance.theia.artemis.cit.tum.de
    - name: acme-cache-http
      protocol: HTTP
      port: 80
      hostname: cache.theia.artemis.cit.tum.de
    - name: acme-repo-http
      protocol: HTTP
      port: 80
      hostname: repo.theia.artemis.cit.tum.de

gatewayClass:
  create: true
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: theia-shared-gateway
    namespace: envoy-gateway-system

envoyProxy:
  create: true
  name: theia-shared-gateway
  namespace: envoy-gateway-system
  spec:
    provider:
      type: Kubernetes
      kubernetes:
        envoyService:
          annotations:
            metallb.io/address-pool: ingress
            metallb.io/loadBalancerIPs: 131.159.88.82

managedCertificates:
  enabled: true
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-gateway
  certificates:
    - name: landing-page-cert
      secretName: landing-page-cert-secret
      hostname: theia.artemis.cit.tum.de
    - name: service-cert
      secretName: service-cert-secret
      hostname: service.theia.artemis.cit.tum.de
    - name: instance-cert
      secretName: ws-cert-secret
      hostname: instance.theia.artemis.cit.tum.de
    - name: cache-cert
      secretName: cache-cert-secret
      hostname: cache.theia.artemis.cit.tum.de
    - name: repo-cert
      secretName: repo-cert-secret
      hostname: repo.theia.artemis.cit.tum.de

gatewayAcmeIssuer:
  enabled: true
  name: letsencrypt-prod-gateway
  email: ls1.itg@in.tum.de

wildcardTLSSecret:
  create: true
  name: static-theia-cert
  namespace: gateway-system
